#!/usr/bin/env bash
#this Bash script gives information about the school file
#using if and else (forbidden else and case)
#this Bash script should check if the file exists and print:
#if the file exists: school file exists
#if the file does not exist: school file does not exist
#If the file exists, print:
#if the file is empty: school file is empty
#if the file is not empty: school file is not empty
#if the file is a regular file: school is a regular file
#if the file is not a regular file: (nothing)

i=1
while [ $i -le 100 ]
do
	if [ $((i%5)) -eq 0 ] && [ $((i%3)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 3)) == 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) == 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	i=$(( i+1 ))
done
