#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd.

#Your script should only display:

#username
#user id
#Home directory path for the user
#Requirements:

#You must use the while loop

ls /etc/passwd

while read -r line
do
	echo "$line" | cut -f 1,3,6 -d ':'
done < "$ls"
