#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

ls=/etc/passwrd
while IFS=":" read -r a1 a2 a3 a4 a5 a6 a7
do
	echo "The user $a1 is part of the $a2 gang, lives in $a3 and rides $a4. $a5's place is protected by the passcode $a6, more info about the user here: $a7"

done < "$ls"
	
