#!/usr/bin/env bash
#this script prints best school from 1 to 10 except 4 and 8 place

i=0
while [ $i -le 9 ]
do
	if [ $i -eq 3 ]

	then
		echo "bad luck"
	elif [ $i -eq 7 ]

	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$(( i+1 ))

done
