#!/usr/bin/env bash
#this script prints numbers from 1 to 20  except 4,9 and 17 place

i=0
while [ $i -le 20 ]
do
	case $i in

	5)
		echo "bad luck from China" ;;
	10)
		echo "bad luck from Japan" ;;
	18)
		echo "bad luck from Italy" ;;


	esac
	echo $i
	i=$(( i + 1 ))
done
