#!/usr/bin/env bash
#this Bash script displays the time for 12 hours and 59 minutes.display hours from 0 to 12.display minutes from 1 to 59

i=0

while [ $i -le 12 ]

do

	echo "Hour: "$i

	a=1

	while [ $a -lt 60 ]

	do
		echo "$a"

		a=$(( a + 1 ))
	done

	i=$((i + 1))
done
