#!/usr/bin/env bash
#this Bash script gives information about the school file
#using if and else (forbidden else and case)
#this Bash script should check if the file exists and print:
#if the file exists: school file exists
#if the file does not exist: school file does not exist
#If the file exists, print:
#if the file is empty: school file is empty
#if the file is not empty: school file is not empty
#if the file is a regular file: school is a regular file
#if the file is not a regular file: (nothing)

i="school"
if [ -e "$i" ]
then
	echo "$i file exist"
       
        if [ -s "$i" ]
	then
		echo "$i file is not empty"
	else
		echo "$i file is empty"
	fi
	if [ -f "$i" ]
	then
		echo "$i is a regular file"
	fi
else 
	echo "$i file does not exist"
done
